# Generated by Django 5.2.1 on 2025-06-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_first_name_user_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_time',
        ),
    ]
